### ISSUE TITLE
`SetMember Lift (Lift IO) r` doesn't seem to be sufficient to line up the function context for lift.

### ISSUE THREAD

**Issue by AndrewRademacher** [suhailshergill/extensible-effects#62] opened 2016-02-24 00:18 UTC
I'm currently isolating IO parts of my software into Eff. In the process I've encountered to seemingly (to me) identical usages and only in one can the function's context be aligned. I've attempted many variants, including a "Getter" effect that just reads lines off the console which also fails. I've tried the Logger effect as a `data Logger n = Logger String n deriving (Tapeable, Functor)` I've tried with concrete types and with quasi generic types, even supplying the `putStrLn` call in the `send . inj` statement. My hope is that I've just done something silly, but I don't see how these two examples differ in a way that is substantive enough to cause the compile to break.

Example One (this one works fine):
```haskell
main :: IO ()
main = do
   pool <- HP.acquire (4, 60.0, hset)
   r <- runLift $ runHasql pool $
      {-db $ appendMessage "Hello World!"-}
      db $ getMessage 3
   print r
   where
      hset = H.settings "localhost" 5432 "andrew" "" "test_eff"

data Hasql n
   = forall a. Hasql (H.Session a) (a -> n)
   deriving (Typeable)

deriving instance Functor Hasql

db :: (Member Hasql e) => H.Session a -> Eff e a
db act = send . inj $ Hasql act id

runHasql
   :: SetMember Lift (Lift IO) r
   => HP.Pool -> Eff (Hasql :> r) a -> Eff r (Either HP.UsageError a)
runHasql pool = loop
   where
      loop = freeMap
               (return . Right)
               (\u -> handleRelay u loop act)
      act (Hasql s k) = (lift $ HP.use pool s) >>= \case
         Left  e -> return $ Left e
         Right v -> loop (k v)
```

Example Two (this one doesn't work):
```haskell
main :: IO ()
main = do
   r <- runLift $ runConsoleLogging $ do
      logM ("Hello"::String)
      logM ("World"::String)
      return (1 + 2)
   print (r::Int)

data Logger n
   = Logger String (() -> n)
   deriving (Typeable)

deriving instance Functor Logger

logM :: (Member Logger r) => String -> Eff r ()
logM msg = send . inj $ Logger msg id

runConsoleLogging
   :: SetMember Lift (Lift IO) r
   => Eff (Logger :> r) a -> Eff r a
runConsoleLogging = loop
   where
      loop = freeMap
               return
               (\u -> handleRelay u loop act)
      act (Logger msg k) = do
         lift $ putStrLn msg       -- compile error is here
         loop (k ())
```

The error:
```
/Users/andrew/src/test-eff/src/ConsoleExample.hs:43:10:
    Could not deduce (extensible-effects-1.11.0.3:Data.OpenUnion.Internal.Base.MemberUImpl
                        extensible-effects-1.11.0.3:Data.OpenUnion.Internal.OpenUnion2.OU2
                        Lift
                        (Lift IO)
                        r)
      arising from a use of ‘lift’
    from the context (SetMember Lift (Lift IO) r)
      bound by the type signature for
                 runConsoleLogging :: SetMember Lift (Lift IO) r =>
                                      Eff (Logger :> r) a -> Eff r a
      at /Users/andrew/src/test-eff/src/ConsoleExample.hs:(35,7)-(36,36)
    In the expression: lift
    In a stmt of a 'do' block: lift $ putStrLn msg
    In the expression:
      do { lift $ putStrLn msg;
           loop (k ()) }
```

**Comment by suhailshergill** [comment] 2016-02-24 05:23
@AndrewRademacher for the working example could you please provide a self-contained gist/example (including dependencies and language extensions)?
similarly, for the failing example.

once i've got the self-contained  positive and negative examples i would be able to dig in. off the top of my head, i'm not sure what the problem is (i've got a few guesses, but it would be faster to test them against the compiler).

**Comment by AndrewRademacher** [comment] 2016-02-24 16:22
@suhailshergill, absolutely, I've actually already got the project in a git repo. Available at https://github.com/AndrewRademacher/test-eff.

The working Hasql example is at https://github.com/AndrewRademacher/test-eff/blob/master/src/HasqlExample.hs.

The failing console logging example is at https://github.com/AndrewRademacher/test-eff/blob/master/src/ConsoleExample.hs.

The project is stack-friendly, so you will get exactly the right dependencies.

**Comment by suhailshergill** [comment] 2016-02-26 11:28
@AndrewRademacher thanks for that. this week has been quite busy, but I will look into this over the weekend.

**Comment by suhailshergill** [comment] 2016-02-27 21:57
@AndrewRademacher see AndrewRademacher/test-eff#1
merging that in should close this issue as well.

**Closed** 2016-02-28 00:53 UTC
